### ISSUE TITLE
Re-consider recommendation of rdkafka (prefer kafkajs) 

### ISSUE THREAD

**Issue by holly-cummins** [nodeshift/nodejs-reference-architecture#25]
My IBM Garage team prefer kafkajs (https://kafka.js.org) to rdkafka. The developer user experience is better with kafkajs, because of its pedigree, and it seems to have more maintenance activity. It also is more portable. kafkajs looks to have surpassed node-rdkafka in terms of npm downloads (although that metric is an imperfect metric of project value!). 

Counter-arguments:

- When we discussed it,  @jgorzins pointed out that kafkajs is not yet listed on https://cwiki.apache.org/confluence/display/KAFKA/Clients#Clients-Node.js
- Incumbency: rdkafka is still widely and strongly recommended on IBM resources. It's clearly still widely used, even if momentum is in the process of shifting.

**Comment by wtrocki** [comment]
Backing up this suggestion. We also use Kafka.js

**Comment by mhdawson** [comment]
We should loop back with the messaging teams within Red Hat and IBM to see if their opinions have changed.  I'll have to dig out the contacts to that we can do that.

@cescoffier as the RH reactive lead I think you have some good insight as to what we should be considering as well. Can you add your comments ?

**Comment by cescoffier** [comment]
There are a few features that should be supported:

* Auto and Manual offset commit (with a clear definition of the auto-commit as it may not work with async processing - see https://quarkus.io/blog/kafka-commit-strategies/)
* Java-compliant partitioning
* Avro support 
* Compression support (GZIP but also Snappy)
* JSON object support
* tombstone support (null value)
* Rebalance hooks (and how can we commit eagerly during a rebalance)
* Shutdown hook
* Possibility to introduce a data store on reception to implement idempotence and exactly-once delivery
* Kafka transaction support

**Comment by Nevon** [comment]
KafkaJS developer here. Glad to hear that you're having positive experiences with KafkaJS, @holly-cummins!

@cescoffier: In regards to your list of features that you'd need in order to feel comfortable recommending KafkaJS, here are my notes. Most of these are supported, some with caveats, and a few I don't really understand and would like some clarification on.

> Auto and Manual offset commit

Both are supported in KafkaJS.

> Java-compliant partitioning

The default partitioner that we ship with is not Java compatible, but we do ship a `JavaCompatiblePartitioner` that can be used: https://kafka.js.org/docs/producing#default-partitioners

In some future major version, we'll probably change the default to be the JavaCompatible one.

> Avro support (with both the Confluent and Apicurio registry)

We consider this to be outside of the scope of the client. We do provide a library for integrating with the Confluent schema registry, with support for not just Avro, but also Protobuf and JSON Schema: https://github.com/kafkajs/confluent-schema-registry/

> Compression support (GZIP but also Snappy)

We support gzip, Snappy, lz4 and zstandard. https://kafka.js.org/docs/producing#a-name-compression-a-compression

> JSON object support

This one I don't really understand what it means. Maybe you can expand on it?

If you pass in an object into `producer.send`, it will be serialized using `JSON.stringify()`, which will call the objects `toJSON` method. When you consume the message, you can toss that into `JSON.parse` to get back the deserialized object.

> tombstone support (null value)

Kind of the same thing here. We do support tombstones in the sense that you can send a null value, and when we consume a null value, that is not passed to the userland code. Is that what you mean by support, or is there something else?

> Rebalance hooks (and how can we commit eagerly during a rebalance)

This one we don't really support today.

> Shutdown hook

Can you re-phrase this one in terms of what you want to achieve? We don't base our API around hooks in general, in contrast to how librdkafka does it.

> Possibility to introduce a data store on reception to implement idempotence and exactly-once delivery

The interceptor pattern that's used in the Java client, which I guess is how you'd think of implementing this, is not how we design KafkaJS. In my mind, this is a higher-level concern that's easily implemented on top of the client. Conceptually it's as simple as:

```ts
const createPersistingMessageHandler = (eachMessageFn) => async ({ message, topic, partition, offset, ...rest }) => {
  // check persistence to see if message has already been processed or whatever other logic you want
  // then delegate back to user handler if the message should be processed
  return eachMessageFn({ message, topic, partition, offset, ...rest })
}

const eachMessage = createPersistingMessageHandler(async ({ message }) => {
  await processMessage(message)
})

await consumer.run({ eachMessage })
```

Maybe there are some specific requirements here that make it difficult to implement this with KafkaJS, and if so, I'd love to hear what those are, but conceptually this isn't something that we think belongs inside the client itself, and at least as of our current thinking, it doesn't require any special APIs that aren't available.

> Kafka transaction support

This is supported, but it needs some love. There are some open bugs here, but since none of us core maintainers have had a need for EoS, we haven't had a chance to really devote time to investigate and sort those issues out. I would love it if some community member with a vested interest in this would take it upon themselves to make this 100% solid.

**Comment by cescoffier** [comment]
Thanks @Nevon for this very detailed reply. First, I'm not a Node developer, so when I listed the feature, I didn't check which ones were and were not implemented in the various libraries. 

It looks to me that kafka.js checks all the boxes (more on the rebalance later)

> JSON object support

It's exactly what you mentioned. It should encode the object into JSON and allows reading the data as JSON. It's natural in the node world, let's say it's less natural in other languages. 

> Shutdown hook

This is the ability to commit processed records before being shut down. Basically, the ability to implement a graceful shutdown and avoid record loss and reduce the likeliness of duplicates. 

> Rebalance listeners

About the rebalance listeners, which is more or less the only missing feature. When a rebalance happens (new consumer, or departure), Kafka will _rebalance_. Involved consumers will be notified that some of the partitions they are assigned to may not be theirs anymore and some new partitions would need to be handled. Hooks allow, typically in the first case, to commit pending records. You can't commit the record just after processing, as you may send too many commits which would be slow. So, you need to batches. Without that ability, we can see duplicates (it's all good, as Kafka apps generally support that), as the already processed records (uncommitted) may be handled by another consumer. Also, if you are not notified, you may end up committing offset on a partition not assigned to you anymore. I don't know how the client would react to this (just a failure maybe?).

**Comment by Nevon** [comment]
> This is the ability to commit processed records before being shut down. Basically, the ability to implement a graceful shutdown and avoid record loss and reduce the likeliness of duplicates.

Ah, I see. This is supported. `consumer.disconnect` will wait for ongoing work to finish before shutting down. Same for `producer.disconnect`, which will wait for any in-flight requests before disconnecting.

> About the rebalance listeners

Right. I'd have to look into exactly what our semantics are on this, but in general the way the client becomes aware of this is that it gets an error response to the heartbeat request. In the client, we then skip any remaining messages and rejoin the group (which gives us new assignments). KafkaJS has two different interfaces towards the user, one where the user passes in a function that is applied to each message (named `eachMessage`) - in this interface we essentially just stop calling the user-provided function with the remainder of the messages. In the `eachBatch` interface we hand the user a batch of messages from a partition. This allows for more complex use-cases, but also delegates more responsibility to the user. In this case the user has the ability to heartbeat themselves, which allows them to become aware of rebalances, and it's also up to them to decide when they want to commit offsets.

**Comment by helio-frota** [comment]
@Nevon hi, 

About SASL Support
 - OAUTH Bearer
 - SASL_PLAIN
 - SASL_SCRAM-SHA512
 - SASL_SCRAM-SHA256

I saw the code here https://github.com/tulios/kafkajs/tree/master/src/broker/saslAuthenticator 
Question: all those SASL approaches are production-ready?

**Comment by Nevon** [comment]
Yes, they are all tested and are used in production.

**Comment by mhdawson** [comment]
Closed by https://github.com/nodeshift/nodejs-reference-architecture/pull/72

**Comment by eladchen** [comment]
For anyone stumbling here.

Not sure this changes anything, but worth knowing about: https://github.com/tulios/kafkajs/issues/1303
