### ISSUE TITLE
First draft of API definition

### ISSUE THREAD

**Issue by mhdawson** [nodeshift/nodejs-reference-architecture#73]

**Comment by mhdawson** [comment]
I think this is covered by https://github.com/nodeshift/nodejs-reference-architecture/blob/main/docs/functional-components/rest-api-development.md, closing.  @InfoSec812. @wtrocki let me know if that was not the right thing to do.

**Comment by InfoSec812** [comment]
@mhdawson Looks pretty good to me. I would make 2 comments:

1. Instead of using @stoplightio/prism-http, it is usually easier to use @stoplightio/prism-cli which does not require writing code

2. I would update references to OpenAPI v3.0 to reference both OpenAPI v3.0 and v3.1 as 3.1 is a technically superior specification.

**Comment by mhdawson** [comment]
@wtrocki since you put together most of the content on the API section, would like your confirmation on suggestions above

**Comment by wtrocki** [comment]
+1 for all suggestions
